### ISSUE TITLE
accountingservice docker image is not updated after the  recent PR got merge

### ISSUE THREAD

**Issue by ragigeo** [open-telemetry/opentelemetry-demo#1745]
# Question
Hello Team,
I am also facing the same issue which was fixed in below PR https://github.com/open-telemetry/opentelemetry-demo/issues/1692

But seems like the docker images not build after the  PE merge. As a result still I am getting similar issue. Please help. Thanks 
https://hub.docker.com/layers/otel/demo/1.11.1-accountingservice/images/sha256-1cbf6a768162a74397c2ea19430aa6557df464cbe2ab174e182149d275abd41c?context=explore

**Comment by julianocosta89** [comment]
Hello @ragigeo 👋🏽 

You are correct, the new image wasn't published yet.
We are planning to have a release later next week.
The issue should be solved with the new release, but for now, if you would like, you can build the image locally by running the following in the root folder of the proj:

```
docker compose build accountingservice
```

**Comment by ragigeo** [comment]
> Hello @ragigeo 👋🏽
> 
> You are correct, the new image wasn't published yet. We are planning to have a release later next week. The issue should be solved with the new release, but for now, if you would like, you can build the image locally by running the following in the root folder of the proj:
> 
> ```
> docker compose build accountingservice
> ```

Hello @julianocosta89 
Seems like the image is still not published. We are using the yaml file to deploy. It would be really great if updated image get published Thanks
