### ISSUE TITLE
No graphs for "Diagnosing memory leaks" scenario

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-demo#839]
# Bug Report

Which version of the demo you are using? (please provide either a specific
[commit
hash](https://github.com/open-telemetry/opentelemetry-demo/commits/main)
or a specific
[release](https://github.com/open-telemetry/opentelemetry-demo/releases)).

Current main 02837fe7b71dd3b85db0efb253a97a693b5d5e3a - it downloads 1.4.0-beta images.

## Symptom

**What is the expected behavior?**

Data similar to https://opentelemetry.io/docs/demo/scenarios/recommendation-cache/

**What is the actual behavior?**

Following charts are not displayed under demo dashboard http://localhost:8080/grafana/dashboards
![image (3)](https://user-images.githubusercontent.com/5972917/231737528-ddb9be2f-e7a2-4ed8-b0a2-9e5f5a246924.png)

Recommendation Service (CPU% and Memory)
Service Latency (from SpanMetrics)
Error Rate

## Reproduce

1. Download repository
1. Execute ` docker compose up` (note it will download 
1. Enable `recommendationCache` feature flag
1. Wait some time (tested 1h+)

## Additional Context

Tested on Windows 10 with Docker with Linux containers.

**Comment by pellared** [comment]
Most of graphs in "OpenTelemetry Collector" dashboard also has no data.

**Comment by LyndonZhao** [comment]
Hi, Mr. Kielek
I met the same problem.
I wonder if you resolve this problem?

**Comment by dbcummings3174** [comment]
I have a similar problem in that I don't have any data in the recommendation graphs. I noticed that the metric runtime_cpython_cpu_time is not available in Prometheus. I only have runtime_cpython_cpu_time_seconds_total.

**Comment by mrcazzim** [comment]
It might be just a metric name mismatch in Grafana vs Prometheus. For example for the latency graph click on its title, edit, and replace the metric name duration_milliseconds_bucket with duration_bucket in all four queries. The error rate one might need to be updated to calls instead of calls_total.

Notice also that the $service variable might need to be updated (go to dashboard setup > variables). If you update this variable definition to 'label_values(service_name)' the 'service' drop down menu on top right of the dashboard will show all services for selection (it won't work for all graphs though e.g. the Recommendations Count graph will obviously only work with the recommendation service selected at the drop down.

**Comment by austinlparker** [comment]
Closing this as part of issue cleanup. If there's anything that needs to be done, please create a new issue.

**Comment by pellared** [comment]
@austinlparker Can you please reopen it? I do not look that the bugs have been addressed.

**Comment by austinlparker** [comment]
Can you provide a repro case for 1.8? I feel like this was fixed.

**Comment by pellared** [comment]
> Can you provide a repro case for 1.8? I feel like this was fixed.

Please assign it to me. I will take a look tomorrow or on Wednesday if the issue still exists.

**Comment by pellared** [comment]
@austinlparker It is fixed. Feel free to close.

**Comment by jas-atwal** [comment]
@pellared the problem still exists.

I have run a `helm repo upgrade` and then `helm upgrade <release>`

Then when I run `helm history <release>` the app version is still the same.

REVISION	UPDATED                 	STATUS    	CHART                    	                   APP VERSION	DESCRIPTION     
1       	Thu Feb 29 10:25:31 2024	superseded	opentelemetry-demo-0.29.0	   1.8.0      	         Install complete
2       	Sun Mar 10 18:40:00 2024	deployed  	opentelemetry-demo-0.29.0	   1.8.0      	         Upgrade complete

Can this issue please be reopened and looked into for resolution.
